### PR TITLE
Support for Gradle building, installing, and jitpack

### PR DESCRIPTION
**Pull request by Tom-Ski**
Allows for jitpack and local Gradle building which is handy as maven is not being deployed. No additional work required.

Minor changes:
gitIgnore update for IDEA and Gradle imports.

### CODE REVIEW

**Comment by badlogic** [comment]
Btw, what do you mean with "Maven is not being deployed"? We release snapshots of the beta branches and occasionally release release versions.

**Comment by Tom-Ski** [comment]
When I latest checked the latest release was January to central. And regrading snapshots I think they may have been down for a few months, April seems to be the latest there on the 3.8 builds. 
 But as there is no history I can't confirm this :(

https://mvnrepository.com/artifact/com.esotericsoftware.spine/spine-libgdx

Handy to have this anyway, we've used some internal patches to the runtimes whilst waiting for spine to update (to new LibGDX version for example), and jitpack makes this trivial to swap between the two.

**Comment by badlogic** [comment]
Well, I blame you that we now also have Gradle in the repo. Thanks, I hate
it :D

**Comment by Tom-Ski** [comment]
I noticed you already had npm, so it couldnt be any worse

**Pull request merged**
