### PR TITLE
Fixes the situation where the timeline, which is not attachment type,…

### PR DESCRIPTION
**Pull request by lolisia**
… mixes with Setup

Fixes the situation where the timeline, which is not attachment type, mixes with Setup

### CODE REVIEW

**Comment by NathanSweet** [comment]
AnimationState is very complex and there are many scenarios it needs to support. it's very easy to break other scenarios when making a change. Can you please show the scenario that doesn't work right which this PR fixes?

**Comment by lolisia** [comment]
When attachment timeline mixing with Setup Pose, '**blend**' variable is written to MixBlend.Setup, and subsequent **AnimationState.Subsequent** timelines are all mixed with MixBlend.Setup.

My guess is that if it's not an AttachmentTimeline or a DrawOrderTimeline, you'll need to use the value of the '**blend**' variable you determined above on the Timeline Loop, **not MixBlend.Setup**.

**Comment by lolisia** [comment]
Please note that due to company rules, I cannot upload resources under development.

It is thought that this occurs when A → B → C SetAnimation has a longer Mix Duration of B → C than the playback time of A → B section.

When B → C Mix, Timeline such as Rotate, Translate, etc. was expected not to mix with Setup Pose. However, when the Mix Duration is long after migration with Spine 3.8 Runtime, it is operating to mix with Setup Pose in most sections.

**Comment by NathanSweet** [comment]
Thanks for the explanation. I believe you are right -- an attachment timeline should not change the blend used for other timelines. We've made the changes for all runtimes. Cheers!

**Pull request closed without merging**
