### PR TITLE
[cocos2dx] Add debug draw for SP_ATTACHMENT_MESH

### PR DESCRIPTION
**Pull request by AIGRIND-LLC**

### CODE REVIEW

**Comment by badlogic** [comment]
Thanks, this looks great! May I ask you to sign our [CLA](http://esotericsoftware.com/files/cla.txt) so we can publish your changes? Just fill in the details and send it to contact@esotericsoftware.com.

**Comment by AIGRIND-LLC** [comment]
Done!

**Comment by badlogic** [comment]
Thanks! I have to merge this with the 3.6-beta branch instead of master.
Will do sometime this week.

**Comment by badlogic** [comment]
I've added debug meshes rendering to the 3.6-beta branch, see https://github.com/EsotericSoftware/spine-runtimes/commit/137f95a20fd842aba277deeab5a36a1c1f2a72bc

**Pull request closed without merging**
