### PR TITLE
[spine-ts][player] Fix skeleton bounds now incorporate clippings

### LINKED ISSUE #2219: [player] Take clipping into account when calculating animation viewport
https://github.com/EsotericSoftware/spine-runtimes/blob/6661ae9322986c84267f7b4b71d66d332dad6d29/spine-ts/spine-player/src/Player.ts#L762

I suggest to calculate viewport size by clipping, but not min-max vertices. Sometimes animation goes out of bounds and player fits viewport size to not visible parts. It's unexpected behaviour for me, so I have to setup viewport manually which is taking much time and exhausting. 
See example, I expect to see these two animations in same bounding box, but 2nd orange jump outside of bottom border

(Could try to provide PR later if you agree with idea. But only for JS platform)

image
image

### PR DESCRIPTION
**Pull request by Disorrder**
Fixes #2219 
Calculate only bounding of clipping attachments, if they exist. 
Example: Violet border is debug of clipping

**Before:**
image
**After:**
image

Spineboy
**Before**
image
**After**
image

### CODE REVIEW

**Comment by Disorrder** [comment]
Not sure it is totally correct, because in spineboy animation clipping applies only for boy, but portal is visible and should be included in bounding. But idk how to recognise clipped components
image

**Comment by badlogic** [comment]
Ah, yes, that won't work I'm afraid. What needs to be done is replicating large parts of the `SkeletonRenderer` logic:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-ts/spine-webgl/src/SkeletonRenderer.ts#L65

The bounds need to be evaluated by getting the min/max x/y for clipped region and mesh attachments. Basically, the `SkeletonRenderer.draw()` method needs to be duplicated. That shouldn't be done in `getBounds()` I think, but rather in the Player itself. Other people's projects rely on `Skeleton.getBounds()` not taking into account clipping attachments.

**Comment by Disorrder** [comment]
Thanks for fast replies!
But viewport size also relies on `Skeleton.getBounds()`. And any other projects could rely on this behaviour 🤔 . Do you think it should use new bounding method? Like getBoundsVisible or something?
Did I understand you correct? Viewport size should be calculated from clipped regions and only _visible_ meshes that aren't clipped.
I don't think we really need to repeat draw method, just need to filter all attachments that aren't clipped and clipping regions itself, that's it. But I still not sure how to recognise is element clipped or not. Are `slotRangeStart `, `slotRangeEnd` responsible for that? Multiple clip regions are not supported, right? Or they just somehow sorted 🤔 
I've just started to use your player couple days ago, haven't dived too deep yet.

**Comment by davidetan** [comment]
@Disorrder Thanks for you PR and the discussion.
This inspired us to change `Skeleton.getBounds()` in all our runtimes.
Now the method gets an additionional `SkeletonClipping` parameter. If passed, the bounds are calculated taking clipping attachments into consideration.
You can see the updates to the Player and TS runtime here: 03f8f67 and f309722.

**Pull request closed without merging**
