### PR TITLE
[libgdx] spine-libgdx AssetManager support

### PR DESCRIPTION
**Pull request by Heroico**
Hi there!

I wrote a utility class to load SkeletonData with LibGDX's Asset Manager. This may be helpful for streamlining asset loading and management through libGDX's infrastructure.

### CODE REVIEW

**Comment by hermith** [comment]
Would love this. Hoping it gets merged soon!

**Comment by NathanSweet** [comment]
See also #266

**Comment by Heroico** [comment]
So... Is there anything I could do to get this merged? i.e.:Make the code closer to the guidelines, squash the commits?

**Comment by raeleus** [comment]
Whatever became of this? I find that this code is exactly what I need for my current project.

**Comment by NathanSweet** [comment]
Sorry, this should never have been closed! My guess is that it was closed automatically when the `EsotericSoftware:master` branch was deleted (we moved to using version names for branches). We'll get it implemented in 3.8.

**Comment by raeleus** [comment]
Thanks for the quick response!

**Pull request closed without merging**
