### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by badlogic** [comment]
Thanks, what compiler and flags are you using to get the warnings?

**Comment by minggo** [comment]
I think you can just use Xcode 9 to compile it. And i think it may exist on other Xcode versions. As you see, there are two types of warnings:

* declare shadow variables
* not explicit assign one type to another and may cause value lost, for example `unsigned long` -> int

**Comment by minggo** [comment]
@badlogic any problem of this PR?

**Comment by badlogic** [comment]
Sorry, no problem with the PR. I overlooked it :D

**Comment by minggo** [comment]
Thanks

**Pull request merged**
