### PR TITLE
[spine-ts] Fix screen blendmode 

### PR DESCRIPTION
**Pull request by tionkje**
I had an issue with the screen blendmode

In spine it looked like this
Screenshot from 2022-01-20 11-01-53

And in webgl it looked like this
Screenshot from 2022-01-20 11-04-49

Searching around i found this answer
https://stackoverflow.com/a/23306083

It needed a split of the destination color and alpha blendfunc and resulted in this
Screenshot from 2022-01-20 11-02-01

which seems more like what is shown in spine

### CODE REVIEW

**Comment by badlogic** [comment]
Hm, we use the exact same blend equation settings in libGDX/Spine and spine-webgl. Is your test running on a transparent canvas by any chance?

**Comment by tionkje** [comment]
This is in the barebones example (spine-ts/spine-webgl/example/barebones.html)

where i re-exported the raptor with the back leg blending changed to screen

and these changes to test overlap with other skeletons

```diff
--- a/spine-ts/spine-webgl/example/barebones.html
+++ b/spine-ts/spine-webgl/example/barebones.html
@@ -19,8 +19,10 @@
                        loadAssets(canvas) {
                                // Load the skeleton file.
                                canvas.assetManager.loadBinary("assets/spineboy-pro.skel");
+                               canvas.assetManager.loadBinary("assets/raptor-pro.skel");
                                // Load the atlas and its pages.
                                canvas.assetManager.loadTextureAtlas("assets/spineboy-pma.atlas");
+                               canvas.assetManager.loadTextureAtlas("assets/raptor-pro.atlas");
                        }

                        initialize(canvas) {
@@ -28,22 +30,28 @@

                                // Create the texture atlas.
                                var atlas = assetManager.require("assets/spineboy-pma.atlas");
+                               var atlas2 = assetManager.require("assets/raptor-pro.atlas");

                                // Create a AtlasAttachmentLoader that resolves region, mesh, boundingbox and path attachments
                                var atlasLoader = new spine.AtlasAttachmentLoader(atlas);
+                               var atlasLoader2 = new spine.AtlasAttachmentLoader(atlas2);

                                // Create a SkeletonBinary instance for parsing the .skel file.
                                var skeletonBinary = new spine.SkeletonBinary(atlasLoader);
+                               var skeletonBinary2 = new spine.SkeletonBinary(atlasLoader2);

                                // Set the scale to apply during parsing, parse the file, and create a new skeleton.
                                skeletonBinary.scale = 1;
+                               skeletonBinary2.scale = 1;
                                var skeletonData = skeletonBinary.readSkeletonData(assetManager.require("assets/spineboy-pro.skel"));
                                this.skeleton = new spine.Skeleton(skeletonData);
+                               var skeletonData2 = skeletonBinary2.readSkeletonData(assetManager.require("assets/raptor-pro.skel"));
+                               this.skeleton2 = new spine.Skeleton(skeletonData2);

                                // Create an AnimationState, and set the "run" animation in looping mode.
                                var animationStateData = new spine.AnimationStateData(skeletonData);
                                this.animationState = new spine.AnimationState(animationStateData);
-                               this.animationState.setAnimation(0, "run", true);
+                               // this.animationState.setAnimation(0, "run", true);
                        }

                        update(canvas, delta) {
@@ -51,8 +59,10 @@
                                this.animationState.update(delta);
                                // Apply the animation state to the skeleton.
                                this.animationState.apply(this.skeleton);
+                               this.animationState.apply(this.skeleton2);
                                // Let the skeleton update the transforms of its bones.
                                this.skeleton.updateWorldTransform();
+                               this.skeleton2.updateWorldTransform();
                        }

                        render(canvas) {
@@ -67,6 +77,7 @@
                                renderer.begin();
                                // Draw the skeleton
                                renderer.drawSkeleton(this.skeleton, true);
+                               renderer.drawSkeleton(this.skeleton2, true);
                                // Complete rendering.
                                renderer.end();
                        }
```

**Comment by badlogic** [comment]
Great, I see what I can do about it. Likely a combination of PMA and blend
mode.

**Comment by badlogic** [comment]
Closed in favor of https://github.com/EsotericSoftware/spine-runtimes/pull/2347

**Comment by badlogic** [comment]
This is now fixed in the latest 4.1 and 4.2-beta branch commits as well as the latest 4.1 and 4.2 NPM packages. I rewrote how blend modes are handled entirely, it's now quite a bit cleaner.

**Pull request closed without merging**
