### PR TITLE
[TS] Alien space

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Space aliens! Alien spaces!

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Its about NBSP ( U+00A0 ) . 

Its actually very strange. I cloned spine-runtimes again and I dont see this symbol anywhere. github also does see it as regular space.

**Comment by ivanpopelyshev** [comment]
On another computer, in newest clone found this symbol in another set of files. Am I getting crazy, am I the only one who sees alt+0160 everywhere?

**Comment by ivanpopelyshev** [comment]
OK, i did a clean clone and replaced NBSP to spaces in whole repo. Now its correct.

**Comment by NathanSweet** [comment]
Blame seems to show that it was space before this PR. Don't know what is going on, but merging spaces can't hurt, right? :D

**Pull request merged**
