### PR TITLE
[spine-c] fixes with worldVerticesLength usage.

### PR DESCRIPTION
**Pull request by Hinidu**
Hi!
We've encountered some issues with weighted meshes and I found some mistakes made in #619.
We still didn't get the stable version unfortunately :disappointed: 
I will push my ongoing changes here.

### CODE REVIEW

**Comment by badlogic** [comment]
What do you mean with "you didn't get the stable version"? I'm currently fixing up the remainder of the spine-c runtime. Thanks for your fixes!

**Comment by Hinidu** [comment]
I mean that our game still crashes (even with these fixes) on reading of the skeleton with the weighted mesh.

**Comment by badlogic** [comment]
Oh, could you maybe send us an example spine project/export? Our weighted mesh examples work as intended.

**Comment by Hinidu** [comment]
We fixed some usages of `worldVerticesLength` in our custom code and it doesn't crash now but mesh rendering is broken though.
> Oh, could you maybe send us an example spine project/export? Our weighted mesh examples work as intended.

I can't do that at least now. Perhaps we will just wait your release and sync our code with your again.

**Comment by badlogic** [comment]
You could try to run the goblin or raptor examples in your modified
runtime. If those work for you, then you found a bug not covered by our
changes yet.

**Comment by Hinidu** [comment]
We fixed that! :sunglasses: Look at https://github.com/EsotericSoftware/spine-runtimes/pull/624/commits/274f20102e9f0959596e6b6667d992a1a46e1a92 I will make a PR for spine-csharp (we encountered the same problem in this runtime and now it is fixed) and spine-libgdx (I think it works the same way) in a minute or two.

**Comment by badlogic** [comment]
Awesome! I actually just stumbled across this weird side effect heavy code when enabling pedantic warnings in Clang. @NathanSweet is to smart for his own good! :D

**Comment by NathanSweet** [comment]
Silly C languages!

**Pull request merged**
