### PR TITLE
[Unity] Handle duplicate key

### PR DESCRIPTION
**Pull request by Abedron**
Error was after Apply in example project MixAndMatch

### CODE REVIEW

**Comment by pharan** [comment]
What was the error after Apply in example? I'm not getting it.
Can you post the actual error?
This fix isn't quite right but I have some other suspicions of where it might actually be.
eg https://github.com/EsotericSoftware/spine-runtimes/commit/06a18da27be7a24f5583eb5c1c3ae16563200e5a

**Comment by Abedron** [comment]
After run click to Apply
https://prnt.sc/h4diqp

**Comment by Abedron** [comment]
I have next error with to the same method "Texture rectangle is out of bounds"

Fix for me:

```
Texture2D sourceTexture = ar.GetMainTexture();
Rect r = ar.GetUnityRect(sourceTexture.height);
int width = Mathf.Min(sourceTexture.width, (int)r.width);
int height = Mathf.Min(sourceTexture.height, (int)r.height);
output = new Texture2D(width, height, textureFormat, mipmaps);
output.name = ar.name;
Color[] pixelBuffer = null;
int x = Mathf.Max(0, (int)r.x);
int y = Mathf.Max(0, (int)r.y);
                
pixelBuffer = sourceTexture.GetPixels(x, y, width, height);

output.SetPixels(pixelBuffer);
```

**Comment by pharan** [comment]
Does applying the change I linked fix things for you?
It **should** make it so it doesn't incorrectly enter into the `if (output == null)` block anymore.

The changes you made so far seem to address the symptom but not the cause. This is also pretty hot code (which is why the caching exists) so we hesitate to add unnecessary checks for obviously broken cases. This is not likely to be merged unless the conditions that cause it make sense.

**Comment by Abedron** [comment]
I create reproducible project and send you. You may find a real problem.

**Comment by Abedron** [comment]
New version spine-unity-3_6-2017-10-31 not have problem with apply, but still have problem with skin change.

Download and open `/Scenes/SpineProblem.unity`
https://drive.google.com/open?id=0B2dvOKWhu9WHYlRYZUtHZDBGcjA

After click "Hat" button get an error `Texture rectangle is out of bounds (0 + 801 > 497)`

**Comment by pharan** [comment]
Thanks for sharing the project! I'll check it out.

**Comment by pharan** [comment]
This seems to just be caused by your texture settings being incorrect.
You need to use Full Rect packing whenever you use Sprites to incorporate into Spine skeletons as RegionAttachments. Apart from not knowing what areas might be trimmed out, we also can't tell what other sprites are packed immediately outside.

See the recommended settings here: https://github.com/pharan/spine-unity-docs/raw/master/img/spine-runtimes-guide/spine-unity/mixandmatch-texture-inspector-options.png
It can also be found in the Mix-And-Match documentation. https://github.com/pharan/spine-unity-docs/blob/master/Mix-and-Match.md

We currently don't have the option for using the tight packing. We'll probably implement it soon. There have been recent major changes to Unity Sprite packing that prevented us from committing to the feature previously.

**Comment by Abedron** [comment]
Thanx

**Pull request closed without merging**
