### PR TITLE
[cpp][cocos2dx] Feature/socialpoint custom changes

### PR DESCRIPTION
**Pull request by sp-stefano-lanza**
In the past we added new features and improvements to Spine for cocos2dx. 
To summarize, the main changes were:
* accurate skeleton culling
* delayed atlas texture loading
* option to **not** update an animation when the associated skeleton has been culled

Since recently Spine moved from a C API to a C++ API, weI had to re-add those changes, adapting them to the new API.
I also fixed the VS workspace since it was not building the sample out of the box.
The new C++ API has various issues, such as lack of const correctness, redundant constructors and destructors, etc. Eventual fixes are outside the scope of this PR.

### CODE REVIEW

**Comment by badlogic** [comment]
This looks good. Could you rebase it on the 3.8-beta branch?

**Comment by badlogic** [comment]
@sp-stefano-lanza I've tried to rebase this on 3.8-beta. In `SkeletonRenderer.cpp`, line 277, you call `cocos2d::Director::getInstance()->isAutoCullingEnable()` if `CC_USE_CULLING` is set. This is not part of the official cocos2d-x API. Could you elaborate?

**Comment by sp-stefano-lanza** [comment]
Hi, ```isAutoCullingEnable``` is an extra feature we added tor cocos2dx. I forgot to remove it from the code in this PR. 
Other than that, did you have issues in rebasing this code to 3.8-beta ?

**Comment by badlogic** [comment]
@sp-stefano-lanza no other issues. Could you amend this PR with a fix for the missing API?

**Comment by badlogic** [comment]
I've pushed my rebase to this repo under the `socialpoint` branch. Closing out this PR. Please send a new one based on that branch to resolve the `Director` API issue.

**Pull request closed without merging**
