### PR TITLE
[cocos2d-x] adpater to new renderer in cocos2dx v4

### PR DESCRIPTION
**Pull request by PatriceJiang**
~~Cocos2d-X new renderer for Metal is in developing.  https://github.com/minggo/cocos2d-x/tree/metal-support~~

~~This PR works only on the new renderer, and we may need a new branch, like `3.7-cocos2d-x-v4`.~~

Current metal support branch is https://github.com/cocos2d/cocos2d-x/tree/v4

### CODE REVIEW

**Comment by badlogic** [comment]
This is great! I think it would make the most sense to create an interface for the batcher, and two impleme tations: one for OpenGL, and the other for Metal. The SkeletonRenderer could then select which impleme tation to use. We'd like to avoid a second branch if possible.

**Comment by PatriceJiang** [comment]
The new renderer supports both Metal and GLES as the backend, this PR works on both platforms.  
The problem is that it breaks the compatibility with the `Cocos2d-x-3.x`.

**Comment by badlogic** [comment]
Ah, yes, my fault :) Curious: Metal doesn't support shader compilation at runtime. I see that this PR still uses the GLES shader. How does that work?

I think we could possibly add subdirectories to the `spine-cocos2dx/` dir, e.g. `v3` and `v4`. It seems the base classes can be re-used between cocos2d-x 3 and 4, which would be rather nice. It will take me a while to get to this.

Thanks for the PR!

**Comment by PatriceJiang** [comment]
I have updated this PR,  now it can run on both v3 and v4. 

> Metal doesn't support shader compilation at runtime. I see that this PR still uses the GLES shader. How does that work?

@minggo  can answer your question.

**Comment by minggo** [comment]
Yep, in cocos2d-x, we use a modified [glsl-optimizer](https://github.com/cocos2d/glsl-optimizer) to translate GLES shader to metal shader dynamically.

**Comment by badlogic** [comment]
@minggo @PatriceJiang I've started working on integrating this with our repository today. To my surprise, I noticed that cocos2dx v4 isn't on GitHub.

You have this branch: https://github.com/cocos2d/cocos2d-x/tree/v4-develop

But that one is from 2015.

We can't integrate your PR without having access to cocos2dx v4. Where can we get access?

**Comment by minggo** [comment]
@badlogic currently, the branch is `metal-support`. The final version name is not determined. It is just in alpha0 version, so i think we can do it after it is in beta version. @PatriceJiang will continue to do it after beta version is released

**Comment by minggo** [comment]
@badlogic i think it is time to merge the PR, and @PatriceJiang updated to latest version. We will continue to update it after if we find bugs.

**Comment by Bilalmirza** [comment]
@badlogic any idea when this will be merged?

**Comment by ghost** [comment]
Hello, how is it going ?

How to test it with v4 branch?

**Comment by PatriceJiang** [comment]
@yinjimmy Please check out this PR https://github.com/cocos2d/cocos2d-x/pull/20122

**Comment by badlogic** [comment]
@PatriceJiang I've started working on integrating this. There are a multitude of issues i have to resolve. The biggest one is that we want the spine-cocos2dx source base to be a drop in replacement. Users should not have to cherry pick which sources to copy into their source tree. The code should work for both v3 and v4 as is.

I've already fixed that up in a local branch. v3 works as intended. However, v4 doesn't compile due to multiple issues. E.g.

```
/Users/badlogic/workspaces/esotericsoftware/spine-runtimes/spine-cocos2dx/src/spine/v4/SkeletonTwoColorBatch.cpp:108:56: error: 'newProgram' is a protected member of 'cocos2d::backend::Device'
        auto program = backend::Device::getInstance()->newProgram(TWO_COLOR_TINT_VERTEX_SHADER, TWO_COLOR_TINT_FRAGMENT_SHADER);
                                                       ^
In file included from /Users/badlogic/workspaces/esotericsoftware/spine-runtimes/spine-cocos2dx/src/spine/v4/SkeletonTwoColorBatch.cpp:41:
/Users/badlogic/workspaces/esotericsoftware/spine-runtimes/spine-cocos2dx/example/cocos2d/cocos/renderer/backend/Device.h:79:22: note: declared protected here
    virtual Program* newProgram(const std::string& vertexShader, const std::string& fragmentShader) = 0;
                     ^
/Users/badlogic/workspaces/esotericsoftware/spine-runtimes/spine-cocos2dx/src/spine/v4/SkeletonTwoColorBatch.cpp:109:34: error: no matching constructor for initialization of 'backend::ProgramState'
        auto *programState = new backend::ProgramState(program);
```

I'm working against the official v4 release you put out this week. Any hints would be appreciated.

There are also a bunch of issues with the project setup itself. We do not want to copy our spine-cpp and spine-cocos2dx sources to the cocos2d `editor-support` folder for our example project. I'm working on resolving that as well.

At the end of the day, if you continue to ship our sources with cocos2dx itself, you should be able to just copy the spine-cocos2dx and spine-cpp sources as is to your `editor-support` folder.

The final issue is that your PR is against the 3.7 instead of the 3.8 branch. I'm resolving this as well as we speak.

I'll ping you once I have published my fixes. If you know how to fix the above, let me know.

**Comment by badlogic** [comment]
Quick update, I reverted this commit https://github.com/EsotericSoftware/spine-runtimes/pull/1244/commits/49adebba6cfd61df1dea89dcc9a79489e0846c2b

Next issue is that `ProgramState::getVertexLayout()` doesn't exist. Did you test your PR against the official cocos2d-x v4 release, or is this only tested against a private, internal version of cocos2d-x?

**Comment by badlogic** [comment]
Nevermind, the CMakeList file you modified downloads the v4 beta instead of the release...

But even with the official release, the `ProgramState::getVertexLayout()` method is not available. Looks like I need to go with `_programState->getProgram()->getActiveAttributes()` instead.

**Comment by badlogic** [comment]
I fixed up a bunch of issues and pushed a new branch called `cocos2d-v4`, see https://github.com/EsotericSoftware/spine-runtimes/tree/cocos2dx-v4

I have not succeeded in getting our example project to work with v4 cleanly. I will have to introduce a separate `example-v4` folder to wire things up correctly. This is rather unfortunate, but I see no way around it.

I'd appreciate a review of my commit concerning `ProgramState` and `VertexLayout`. It appears the code you pushed in this PR is not yet quite ready for production.

**Comment by PatriceJiang** [comment]
@badlogic I am sorry that I forgot to update the download link, some APIs had changed. 

According to the issues you pointed out, I dealt with it in another [PR](https://github.com/EsotericSoftware/spine-runtimes/pull/1564).

**Comment by badlogic** [comment]
Thank you! I'm closing this PR out in favor of this one. We'll continue on the cocos2dx-v4 branch. https://github.com/EsotericSoftware/spine-runtimes/pull/1564

**Comment by badlogic** [comment]
@PatriceJiang @minggo I have now finished the integration of cocos2dx V4 support in both the 3.8 and 3.9-beta branches.

I have rebased your contribution on the latest spine-cocos2dx code from the 3.8 branch. Only the `SkeletonBatch` and `SkeletonTwoColorBatch` classes have implementations that are different for v3 and v4. The rest of the code is shared for v3 and v4. This will simplify maintenance going forward.

I was also able to reuse our example code without duplication. I did however have to create separate projects for v3 and v4. The `example-v4` project references `example/Classes`.

I have updated the README.md to indicate how to run our examples for both cocos2dx v3 and v4. The new full CMake build is very nice, making it a lot easier to integrate and test spine-cocos2dx with cocos2dx v4.

However, we are also seeing quite a few regression with the cocos2dx v4 rendering. It would be great if you could give me some hints on how to approach these.

1. Our example scenes do not render correctly on Android. While the `DrawNode` based debug rendering of bones and other skeleton elements work, the actual parts of the skeletons themselves do not render at all. I have tried to debug this but could not find the cause yet.
2. We are seeing massive performance rergressions using the v4 rendering pipeline on all platforms. Our [BatchingExample](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cocos2dx/example/Classes/BatchingExample.cpp) scene runs at 60FPS with cocos2dx v3.  With cocos2dx v4 we see a massive increase in draw calls, leading to very poor performance.  It appears that batching is broken in v4, at least on Windows. The GL calls stats are the same across all platforms, but on iOS and macOS, performance is still good. On Windows, performance degrades heavily even on a super beefy desktop machine.
3. On Windows, we see rendering artifacts for clipped meshes.  This is especially confusing, as the code that's being executed on our end is exactly the same for v3 and v4. It's also puzzling as it only shows up on Windows.

I'd appreciate any hints, especially concering the very heavyperformance regression.

On a related note, I've also updated integration and build instructions. I assume you will continue to ship the spine-cocos2dx sources as part of the cocos2d-x v4 distribution? In that case, maybe we could include instructions on how to upgrade to the latest spine-cocos2dx version in the cocos2dx documentation? We will add this documentation to our repository once you merge the spine-cocos2dx sources into your v4 branch.

Thank you for your help!

**Comment by rh101** [comment]
@badlogic The draw call issue is caused by this line in SkeletonBatch.cpp:

```
SkeletonBatch::SkeletonBatch () {

    auto program = backend::Device::getInstance()->newProgram(positionTextureColor_vert, positionTextureColor_frag);
```

Change it to this:
```
auto program = backend::Program::getBuiltinProgram(backend::ProgramType::POSITION_TEXTURE_COLOR);
```

Shaders created without using the built-in `Program` types are no longer cached, so a new `Program` is created each time you call it with a vertex and fragment shader.  This behavior is different than how Cocos2d-x v3 works.  As a result of this, anything using the unique instances of each `Program` (any `ProgramStates`) will not be batched.

There are two ways to fix this:

1. Use the built-in shader programs if possible (which are cached), and in this case it is possible since the vertex and fragment shader combination you want to use is already defined as the built-in program type `backend::ProgramType::POSITION_TEXTURE_COLOR`.

or 

2. Cache the created `Program`, and re-use it, which is useful in the instance where no predefined Program exists.

Side-note, this does not solve the Android problem.  All Spine animations are invisible when tested on an Android device. :(

**Comment by rh101** [comment]
There's a way to not require a separate `Example` folder for v3 and v4, and there would be no need to specify v3 or v4 in the include statements within the code.  This is the CMakeLists.txt for spine-cocos2dx that I'm using at the moment:

```
get_target_property(COCOS2D_X_VERSION cocos2d VERSION)

if (COCOS2D_X_VERSION VERSION_GREATER_EQUAL 4.0)
	set(SPINE_COCOS_X_VERSION_DIR "v4")
else()
	set(SPINE_COCOS_X_VERSION_DIR "v3")
endif()

set(SPINE_COCOS2DX_HEADER
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/AttachmentVertices.h
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/SkeletonAnimation.h
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/SkeletonRenderer.h
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/spine-cocos2dx.h
    ${CMAKE_CURRENT_LIST_DIR}/${SPINE_COCOS_X_VERSION_DIR}/src/spine/SkeletonBatch.h
    ${CMAKE_CURRENT_LIST_DIR}/${SPINE_COCOS_X_VERSION_DIR}/src/spine/SkeletonTwoColorBatch.h
   )

set(SPINE_COCOS2DX_SRC
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/AttachmentVertices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/SkeletonAnimation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/SkeletonRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/spine/spine-cocos2dx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/${SPINE_COCOS_X_VERSION_DIR}/src/spine/SkeletonBatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/${SPINE_COCOS_X_VERSION_DIR}/src/spine/SkeletonTwoColorBatch.cpp
   )

list(APPEND SPINE_COCOS2DX_SRC ${SPINE_COCOS2DX_HEADER})

add_library(spine-cocos2dx STATIC ${SPINE_COCOS2DX_SRC})

set_target_properties(spine-cocos2dx
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
)

add_dependencies(spine-cocos2dx spine-static cocos2d)

target_link_libraries(spine-cocos2dx 
	PUBLIC spine-cpp 
	PRIVATE cocos2d
)
target_include_directories(spine-cocos2dx 
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}/src
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}/${SPINE_COCOS_X_VERSION_DIR}/src
    )

```

Also, for the CMakeLists.txt in the Example project, the CMakeLists.txt only differs in the bottom section, and this is what I use to support V3.17.1 or below, 3.17.2 and v4 (since they all have slightly different sections):
```
get_target_property(COCOS2D_X_VERSION cocos2d VERSION)

if (COCOS2D_X_VERSION VERSION_GREATER_EQUAL 4.0.0)
    if(APPLE)
        set_target_properties(${APP_NAME} PROPERTIES RESOURCE "${APP_UI_RES}")

        if(MACOSX)
            set_target_properties(${APP_NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/proj.ios_mac/mac/Info.plist")
        elseif(IOS)
            set_target_properties(${APP_NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/proj.ios_mac/ios/Info.plist")
            set_xcode_property(${APP_NAME} ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon")
        endif()

        # For code-signing, set the DEVELOPMENT_TEAM:
        #set_xcode_property(${APP_NAME} DEVELOPMENT_TEAM "GRLXXXX2K9")
    elseif(WINDOWS)
        cocos_copy_target_dll(${APP_NAME})
    endif()

    if(LINUX OR WINDOWS)
        cocos_get_resource_path(APP_RES_DIR ${APP_NAME})
        cocos_copy_target_res(${APP_NAME} LINK_TO ${APP_RES_DIR} FOLDERS ${GAME_RES_FOLDER})
    endif()
elseif(COCOS2D_X_VERSION VERSION_GREATER_EQUAL 3.17.2)
    if(APPLE)
        set_target_properties(${APP_NAME} PROPERTIES RESOURCE "${APP_UI_RES}")
        if(MACOSX)
            set_target_properties(${APP_NAME} PROPERTIES
                                  MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/proj.ios_mac/mac/Info.plist"
                                  )
        elseif(IOS)
            cocos_pak_xcode(${APP_NAME} INFO_PLIST "iOSBundleInfo.plist.in")
            set_xcode_property(${APP_NAME} ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon")
            set_xcode_property(${APP_NAME} DEVELOPMENT_TEAM "")
            set_xcode_property(${APP_NAME} CODE_SIGN_IDENTITY "iPhone Developer")
        endif()
    elseif(WINDOWS)
        cocos_copy_target_dll(${APP_NAME})
    endif()

    if(LINUX OR WINDOWS)
        set(APP_RES_DIR "$<TARGET_FILE_DIR:${APP_NAME}>/Resources")
        cocos_copy_target_res(${APP_NAME} COPY_TO ${APP_RES_DIR} FOLDERS ${GAME_RES_FOLDER})
    endif()
else()
    if(APPLE)
        set_target_properties(${APP_NAME} PROPERTIES RESOURCE "${APP_UI_RES}")
        if(MACOSX)
            set_target_properties(${APP_NAME} PROPERTIES
                                  MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/proj.ios_mac/mac/Info.plist"
                                  )
        elseif(IOS)
            cocos_pak_xcode(${APP_NAME} INFO_PLIST "iOSBundleInfo.plist.in")
            set_xcode_property(${APP_NAME} ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon")
        endif()
    elseif(WINDOWS)
        cocos_copy_target_dll(${APP_NAME} COPY_TO ${APP_RES_DIR}/..)
    endif()

    if(LINUX OR WINDOWS)
        cocos_copy_res(COPY_TO ${APP_RES_DIR} FOLDERS ${GAME_RES_FOLDER})
    endif()
endif()
```

**Comment by minggo** [comment]
@badlogic thanks for your work. We are looking into it. And we will merge it spine runtime into cocos2d-x v4 after all issues are fixed.

**Comment by badlogic** [comment]
@rh101 do I understand correctly that you removed the IDE projects in the v3 `example` folder and got things to work for both v3 and v4 with a single `CMakeList.txt`? I spent time on this today, but couldn't quite make it work. I'd love to get rid of the IDE projects! Could you maybe send your changes as a PR?

**Comment by rh101** [comment]
@badlogic Unfortunately no, that's not what I meant.  The IDE folders can't be removed.  The proj.android is still required, since we can't create that project using CMake, although the project itself does use CMake for the builds.  

The proj.win32/proj.ios_mac/proj.linux folders have a few required files, like main.cpp/.h etc. You can see the section of the root CMakeLists.txt that references files in those folders:
```
if(MACOSX OR APPLE)
    set(APP_UI_RES
    proj.ios_mac/mac/Icon.icns
    proj.ios_mac/mac/Info.plist
    )
    set(PLATFORM_SPECIFIC_SRC
      proj.ios_mac/mac/main.cpp
    )
elseif(LINUX)
    set(PLATFORM_SPECIFIC_SRC
      proj.linux/main.cpp
    )
elseif ( WIN32 )
    set(PLATFORM_SPECIFIC_SRC
      proj.win32/main.cpp
    )
    set(PLATFORM_SPECIFIC_HEADERS
      proj.win32/main.h
      proj.win32/resource.h
    )
elseif(ANDROID)
    set(PLATFORM_SPECIFIC_SRC
      proj.android-studio/app/jni/hellocpp/main.cpp
    )
endif()
```

What I meant was that I noticed an `example` and `example-v4`, but it's possible to only have a single example project that works with both v3 and v4.  Also, the CMakeLists.txt in the spine-cocos2dx is modified in a way so that it's transparent to the app that using it, so no need to have include paths like this:
```
#if COCOS2D_VERSION < 0x00040000
#include <spine/v3/SkeletonBatch.h>
#include <spine/v3/SkeletonTwoColorBatch.h>
#else
#include <spine/v4/SkeletonBatch.h>
#include <spine/v4/SkeletonTwoColorBatch.h>
#endif
```

With the CMakeLists.txt example I posted above, it allows you to simply do this instead:
```
#include <spine/SkeletonBatch.h>
#include <spine/SkeletonTwoColorBatch.h>
```

Anyhow, I'll modify the example project so it works with both v3 and v4 based on what I'm using in my own project, and I'll submit them in a PR, if that helps.

**Comment by badlogic** [comment]
@rh101 ah, yes. Sorry, I misspoke. What I meant was that there's a few differences in the platform specific files (mostly mobile) between v3 and v4. Looking forward to the PR. Thanks for your help!

**Comment by badlogic** [comment]
Thank you everyone! I have finally concluded the work on spine-cocos2dx v4. Wouldn't have been possible without your help. @minggo I believe this could now be included in the cocos2d-x source tree if you still want to include spine-cocos2dx there.

**Pull request closed without merging**
