### PR TITLE
Make JsonRollback results support 3.6 runtime

### PR DESCRIPTION
**Pull request by taigacon**
Make JsonRollback generated results support 3.6 runtime. (3.6.53)

### CODE REVIEW

**Comment by NathanSweet** [comment]
Likely 3.7 JSON will work in 3.6. If you can post 3.7 JSON that doesn't work in 3.6, we'll reopen this issue.

Note that using the JsonRollback tool is not a workflow that you should rely on.

**Comment by taigacon** [comment]
Sorry for the late reply.
The 3.7 json can not work perfectly in 3.6, because of the lack of "x" and "y" field in the "scale“ group.
It seems that editor/runtime will treat the lack as default value.
However, the default values are 1.0/1.0 in 3.7, and 0.0/0.0 in 3.6.

**Comment by taigacon** [comment]
After the translate, the animation of the project skeleton_3.6.53 is broken due to the scale set to 0/0.

[project.zip](https://github.com/EsotericSoftware/spine-runtimes/files/3521739/project.zip)

**Comment by NathanSweet** [comment]
A recent commit has fixed this, please try now (the Skeleton Viewer has been updated) or use this 3.7 JSON:
http://n4te.com/x/416-skeleton_3.7.json

**Comment by taigacon** [comment]
Sure, thanks a lot.

**Pull request closed without merging**
