### PR TITLE
flutter: fix memory cleanup is slow due to not destroying shaders

### PR DESCRIPTION
**Pull request by hantrungkien**

### CODE REVIEW

**Comment by badlogic** [comment]
Good catch, thanks!

**Comment by hantrungkien** [comment]
@badlogic What do I need to add so it can be merged?

**Comment by badlogic** [comment]
Nothing, I pressed the wrong button :/

Merged!

**Comment by hantrungkien** [comment]
@badlogic thanks. When can I get 4.2.3 from pub.dev?

**Comment by badlogic** [comment]
4.2 is currently unstable as we are wrapping up the 4.2 release. I'll publish a new 4.1 tomorrow.

**Comment by hantrungkien** [comment]
@badlogic please release help me

**Comment by badlogic** [comment]
Your fix is incorrect and will result in crashes, as the same image is disposed multiple times with this approach.

**Comment by badlogic** [comment]
I've reverted the fix and instead resorted to cleaning out the list of paints. `ImageShader` instances are not supposed to be disposed manually according to the docs. This should have the same effect once the GC kicks in.

**Pull request merged**
